BG = "#0C1012"; SIDEBAR = "#111619"; SURFACE = "#151B1E"; SURFACE_ALT = "#1A2125"; SURFACE_HOVER = "#20292D"; BORDER = "#283136"; TEXT = "#F5F7F8"; TEXT_MUTED = "#93A0A6"; TEXT_DIM = "#69767C"
ACCENT = "#55D6C2"; ACCENT_HOVER = "#45C5B2"; ACCENT_DARK = "#173A35"; DANGER = "#F07178"; DANGER_DARK = "#3A1E21"; WARNING = "#E1B65F"; WARNING_DARK = "#3A311D"; INFO = "#71A7E8"; INFO_DARK = "#1A2D43"; SUCCESS = "#67D59C"; SUCCESS_DARK = "#18392B"

FONT = "Segoe UI"; FONT_MONO = "Cascadia Mono"; RADIUS = 12; RADIUS_SMALL = 8; SIDEBAR_WIDTH = 232

STATUS_COLORS = {
    "running": (SUCCESS, SUCCESS_DARK), "protected": (SUCCESS, SUCCESS_DARK), "verified": (SUCCESS, SUCCESS_DARK), "contained": (SUCCESS, SUCCESS_DARK), "completed": (SUCCESS, SUCCESS_DARK),
    "degraded": (WARNING, WARNING_DARK), "partial": (WARNING, WARNING_DARK), "suspicious": (WARNING, WARNING_DARK), "investigating": (WARNING, WARNING_DARK), "reappeared": (WARNING, WARNING_DARK),
    "dangerous": (DANGER, DANGER_DARK), "failed": (DANGER, DANGER_DARK), "error": (DANGER, DANGER_DARK),
    "stopped": (TEXT_MUTED, SURFACE_ALT), "idle": (TEXT_MUTED, SURFACE_ALT), "open": (INFO, INFO_DARK), "restored": (INFO, INFO_DARK),
}